export const OPEN_POOL = 'OPEN_POOL';
export const CREATE_DEAL = 'CREATE_DEAL';
export const FUND_DEAL = 'FUND_DEAL';
export const ACCEPT_OR_REJECT_DEAL = 'ACCEPT_OR_REJECT_DEAL';
export const POOL_DURATION_ENDED = 'POOL_DURATION_ENDED';
export const UNREDEEMED_TOKENS = 'UNREDEEMED_TOKENS';
export const VESTING_DEAL = 'VESTING_DEAL';
